version: '2.2'
services:
  application:
    container_name: monito-application
    depends_on:
      - database
    ports:
      - 127.0.0.1:8008:8008
    links:
      - database
  worker:
    container_name: monito-worker
    restart: always
    depends_on:
      - database
    links:
      - database
  database:
    image: mysql:8.0.18
    container_name: monito-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./Infrastructure/DatabaseScripts.sql:/docker-entrypoint-initdb.d/init.sql
  pma:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: monito-pma
    environment:
      - PMA_HOST=database
    ports:
      - 127.0.0.1:8007:80
    depends_on:
      - database
    links:
      - database